"use client";
// import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";

import Sidebar from "@/app/admin/components/Sidebar";
import Navbar from "@/app/admin/components/Navbar";
import { useEffect, useState } from "react";
import { useAuth } from "../api/auth/contexts/AuthContext";
import { useRouter } from "next/navigation";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// export const metadata: Metadata = {
//   title: "Diaspora Admin",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const { accessToken } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!mounted) {
      return;
    }

    // if (!accessToken) {
    //   // Redirect to login page if not authenticated
    //   router.push("/");
    // }
  }, [mounted, accessToken, router]);

  if (!mounted) {
    return null;
  }
  return (
    <div
      className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}
    >
      <div>
        <Navbar />
        <Sidebar />
        <div className="m-8 md:ml-72 mt-16 pt-4">{children}</div>
      </div>
    </div>
  );
}
