import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";

import "./globals.css";
import { NewSessionProvider } from "@/providers/session-provider";
import { ToasterProvider } from "@/providers/toast-provider";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased bg-gray-50",
          fontSans.variable
        )}
      >
        <NewSessionProvider>
          <ToasterProvider />
          <div>
            <div className="">{children}</div>
          </div>
        </NewSessionProvider>
      </body>
    </html>
  );
}
