import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Permissions",
  description: "Generated by Coop",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div>{children}</div>
    </>
  );
}
